### Import libraries

In [16]:
import pandas as pd 
import numpy as np 
import os

### Load datasets for inspection and cleaning

#### 1.) Online shop data

In [2]:
shop_data = pd.read_csv(r"C:\Users\Glemba\Desktop\Kenyan retail analysis\raw_data\kenyan_online_shop_data.csv")
shop_data.head()

,InvoiceNo,CustomerID,Product,Quantity,UnitPrice,TotalPrice,InvoiceDate,Location,CustomerType
0,ORD10000,CUST1076,Sanitary Towels (Pack),1,153.60,153.60,2/17/2023,Umoja,Regular
1,ORD10001,CUST1075,Bread (400g),1,52.55,52.55,02/09/2023,Nairobi,Regular
2,ORD10002,CUST1020,Milk (500ml),1,44.20,44.20,02/01/2023,Roysambu,Regular
3,ORD10003,CUST1181,Sanitary Towels (Pack),1,250.33,250.33,2/22/2023,Ruiru,Budget
4,ORD10004,CUST1079,Sugar (1kg),1,132.24,132.24,4/13/2023,Nairobi,Budget

In [3]:
def basic_checks(shop_data):
    print('-' * 40, 'Shape', '-' * 40)
    print(shop_data.shape)
    print('-' * 40, 'Columns', '-' * 40)
    print(shop_data.columns)
    print('-' * 40, 'Info', '-' * 40)
    print(shop_data.info())
    print('-' * 40, 'Summary statistics(categorical)', '-' * 40)
    print(display(shop_data.describe(include=['str', 'object']).T))
    print('-' * 40, 'Summary statistics(numerical)', '-' * 40)
    print(display(shop_data.describe(include=['int', 'float']).T))
    print('-' * 40, 'Duplicates', '-' * 40)
    print(shop_data.duplicated().sum())
    print('-' * 40, 'Null Values', '-' * 40)
    print(shop_data.isna().sum())
    print('-' * 40, 'Unique Values', '-' * 40)
    print(shop_data.nunique())
    print('-' * 40, 'Data Types', '-' * 40)
    print(shop_data.dtypes)

In [4]:
basic_checks(shop_data)

---------------------------------------- Shape ----------------------------------------
(1500, 9)
---------------------------------------- Columns ----------------------------------------
Index(['InvoiceNo', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'TotalPrice', 'InvoiceDate', 'Location', 'CustomerType'],
      dtype='str')
---------------------------------------- Info ----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   InvoiceNo     1500 non-null   str
 1   CustomerID    1500 non-null   str
 2   Product       1500 non-null   str
 3   Quantity      1500 non-null   int64
 4   UnitPrice     1500 non-null   float64
 5   TotalPrice    1500 non-null   float64
 6   InvoiceDate   1500 non-null   str
 7   Location      1500 non-null   str
 8   CustomerType  1500 non-null   str
dtypes: float64(2), int64(1), str(6)
memory usage: 105.6 KB
None
---------------------------------------- Summary statistics(categorical) ----------------------------------------

             count unique          top freq
InvoiceNo     1500   1500     ORD10000    1
CustomerID    1500    299     CUST1020   11
Product       1500     10  Eggs (Tray)  182
InvoiceDate   1500    271    1/31/2023   24
Location      1500      8      Nairobi  485
CustomerType  1500      3       Budget  921

None
---------------------------------------- Summary statistics(numerical) ----------------------------------------

,count,mean,std,min,25%,50%,75%,max
Quantity,1500.0,1.004667,0.492077,0.00,1.0000,1.00,1.0000,5.00
UnitPrice,1500.0,147.602073,97.613677,29.01,59.5950,124.37,215.2750,366.89
TotalPrice,1500.0,147.188993,116.557819,0.00,57.0925,121.44,217.3975,1152.40

None
---------------------------------------- Duplicates ----------------------------------------
0
---------------------------------------- Null Values ----------------------------------------
InvoiceNo       0
CustomerID      0
Product         0
Quantity        0
UnitPrice       0
TotalPrice      0
InvoiceDate     0
Location        0
CustomerType    0
dtype: int64
---------------------------------------- Unique Values ----------------------------------------
InvoiceNo       1500
CustomerID       299
Product           10
Quantity           6
UnitPrice       1458
TotalPrice      1389
InvoiceDate      271
Location           8
CustomerType       3
dtype: int64
---------------------------------------- Data Types ----------------------------------------
InvoiceNo           str
CustomerID          str
Product             str
Quantity          int64
UnitPrice       float64
TotalPrice      float64
InvoiceDate         str
Location            str
CustomerType        str
dtype: object

#### 2.) Population and housing census

In [5]:
population_data = pd.read_csv(r"C:\Users\Glemba\Desktop\Kenyan retail analysis\raw_data\Kenya population and Housing Census Population households density by county (KE1,DF_POP_CENSUS_COU,1.0).csv")
population_data.head()

,Reference Area (KE),Census Indicators (POP_TOT),Sex (M),Employment status (_T),Time period (2019),Observation,Observation Status,Unit of measure,Unit Multipler,Time Period Comment,Time Series Comment,Dataset Comment,Source
0,KENYA,Total Population,Male,_T,2019,23548056,NaN,Number,Units,NaN,NaN,NaN,Kenya National Bureau of Statistics
1,KENYA,Total Population,Female,_T,2019,24014716,NaN,Number,Units,NaN,NaN,NaN,Kenya National Bureau of Statistics
2,KENYA,Total Population,Total,_T,2019,47564296,NaN,Number,Units,NaN,NaN,NaN,Kenya National Bureau of Statistics
3,NAIROBI,Total Population,Male,_T,2019,2192452,NaN,Number,Units,NaN,NaN,NaN,Kenya National Bureau of Statistics
4,NAIROBI,Total Population,Female,_T,2019,2204376,NaN,Number,Units,NaN,NaN,NaN,Kenya National Bureau of Statistics

In [6]:
def basic_checks(population_data):
    print('-' * 40, 'Shape', '-' * 40)
    print(population_data.shape)
    print('-' * 40, 'Columns', '-' * 40)
    print(population_data.columns)
    print('-' * 40, 'Info', '-' * 40)
    print(population_data.info())
    print('-' * 40, 'Summary statistics(categorical)', '-' * 40)
    print(display(population_data.describe(include=['str', 'object']).T))
    print('-' * 40, 'Summary statistics(numerical)', '-' * 40)
    print(display(population_data.describe(include=['int', 'float']).T))
    print('-' * 40, 'Duplicates', '-' * 40)
    print(population_data.duplicated().sum())
    print('-' * 40, 'Null Values', '-' * 40)
    print(population_data.isna().sum())
    print('-' * 40, 'Unique Values', '-' * 40)
    print(population_data.nunique())
    print('-' * 40, 'Data Types', '-' * 40)
    print(population_data.dtypes)

In [7]:
basic_checks(population_data)

---------------------------------------- Shape ----------------------------------------
(42507, 13)
---------------------------------------- Columns ----------------------------------------
Index(['Reference Area (KE)', 'Census Indicators (POP_TOT)', 'Sex (M)',
       'Employment status (_T)', 'Time period (2019)', 'Observation',
       'Observation Status', 'Unit of measure', 'Unit Multipler',
       'Time  Period Comment', 'Time Series Comment', 'Dataset Comment',
       'Source'],
      dtype='str')
---------------------------------------- Info ----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 42507 entries, 0 to 42506
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Reference Area (KE)          42507 non-null  str
 1   Census Indicators (POP_TOT)  42507 non-null  str
 2   Sex (M)                      42507 non-null  str
 3   Employment status (_T)       42507 non-null  str
 4   Time period (2019)           42507 non-null  int64
 5   Observation                  42507 non-null  int64
 6   Observation Status           0 non-null      float64
 7   Unit of measure              42507 non-null  str
 8   Unit Multipler               42507 non-null  str
 9   Time  Period Comment         0 non-null      float64
 10  Time Series Comment          0 non-null      float64
 11  Dataset Comment              0 non-null      float64
 12  Source                       42507 non-null  str
dtypes: float64(4), int64(2), str(7)
memory usage: 4.2 MB
None
---------------------------------------- Summary statistics(categorical) ----------------------------------------

,count,unique,top,freq
Reference Area (KE),42507,9789,TOWNSHIP,108
Census Indicators (POP_TOT),42507,1,Total Population,42507
Sex (M),42507,3,Male,14169
Employment status (_T),42507,1,_T,42507
Unit of measure,42507,1,Number,42507
Unit Multipler,42507,1,Units,42507
Source,42507,1,Kenya National Bureau of Statistics,42507

None
---------------------------------------- Summary statistics(numerical) ----------------------------------------

,count,mean,std,min,25%,50%,75%,max
Time period (2019),42507.0,2019.000000,0.000000,2019.0,2019.0,2019.0,2019.0,2019.0
Observation,42507.0,13427.492131,287576.046054,0.0,1594.0,3138.0,7078.5,47564296.0
Observation Status,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Period Comment,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time Series Comment,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dataset Comment,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

None
---------------------------------------- Duplicates ----------------------------------------
2016
---------------------------------------- Null Values ----------------------------------------
Reference Area (KE)                0
Census Indicators (POP_TOT)        0
Sex (M)                            0
Employment status (_T)             0
Time period (2019)                 0
Observation                        0
Observation Status             42507
Unit of measure                    0
Unit Multipler                     0
Time  Period Comment           42507
Time Series Comment            42507
Dataset Comment                42507
Source                             0
dtype: int64
---------------------------------------- Unique Values ----------------------------------------
Reference Area (KE)             9789
Census Indicators (POP_TOT)        1
Sex (M)                            3
Employment status (_T)             1
Time period (2019)                 1
Observation                    14793
Observation Status                 0
Unit of measure                    1
Unit Multipler                     1
Time  Period Comment               0
Time Series Comment                0
Dataset Comment                    0
Source                             1
dtype: int64
---------------------------------------- Data Types ----------------------------------------
Reference Area (KE)                str
Census Indicators (POP_TOT)        str
Sex (M)                            str
Employment status (_T)             str
Time period (2019)               int64
Observation                      int64
Observation Status             float64
Unit of measure                    str
Unit Multipler                     str
Time  Period Comment           float64
Time Series Comment            float64
Dataset Comment                float64
Source                             str
dtype: object

#### cleaning

In [8]:
def clean_pipeline(population_data):
    # remove duplicates
    original = len(population_data)
    population_data = population_data.drop_duplicates()
    print(f"Removed {original - len(population_data)} duplicates")

    # drop unnecessary columns
    population_data = population_data.drop(columns=['Observation Status', 'Time  Period Comment', 'Time Series Comment', 'Dataset Comment', 'Employment status (_T)'])
    print(f"Removed unnecessary columns, new shape: {population_data.shape}")
    
    return population_data

In [9]:
clean_pipeline(population_data)

Removed 2016 duplicates
Removed unnecessary columns, new shape: (40491, 8)

,Reference Area (KE),Census Indicators (POP_TOT),Sex (M),Time period (2019),Observation,Unit of measure,Unit Multipler,Source
0,KENYA,Total Population,Male,2019,23548056,Number,Units,Kenya National Bureau of Statistics
1,KENYA,Total Population,Female,2019,24014716,Number,Units,Kenya National Bureau of Statistics
2,KENYA,Total Population,Total,2019,47564296,Number,Units,Kenya National Bureau of Statistics
3,NAIROBI,Total Population,Male,2019,2192452,Number,Units,Kenya National Bureau of Statistics
4,NAIROBI,Total Population,Female,2019,2204376,Number,Units,Kenya National Bureau of Statistics
...,...,...,...,...,...,...,...,...
42502,NYAMIRA NORTH,Total Population,Female,2019,86947,Number,Units,Kenya National Bureau of Statistics
42503,NYAMIRA NORTH,Total Population,Total,2019,167267,Number,Units,Kenya National Bureau of Statistics
42504,NYAMIRA SOUTH,Total Population,Male,2019,76105,Number,Units,Kenya National Bureau of Statistics
42505,NYAMIRA SOUTH,Total Population,Female,2019,82965,Number,Units,Kenya National Bureau of Statistics
42506,NYAMIRA SOUTH,Total Population,Total,2019,159073,Number,Units,Kenya National Bureau of Statistics

#### 3.) inflation rates

In [10]:
inflation_data = pd.read_csv(r"C:\Users\Glemba\Desktop\Kenyan retail analysis\raw_data\kenya_cpi_inflation_rates_2009-01-01_to_2026-09-01.csv")
inflation_data.head()

,Period,Series,Value,Monthly Change (%),Annual Change (%),Category,Region,Data Type
0,2010-01-01,Overall Inflation (National),7.525587,0.224467,7.525587,Overall Inflation,National,Inflation Rate
1,2010-02-01,Overall Inflation (National),5.168363,0.261292,5.168363,Overall Inflation,National,Inflation Rate
2,2010-03-01,Overall Inflation (National),3.975179,-0.186150,3.975179,Overall Inflation,National,Inflation Rate
3,2010-04-01,Overall Inflation (National),3.652441,0.559493,3.652441,Overall Inflation,National,Inflation Rate
4,2010-05-01,Overall Inflation (National),3.863899,0.204006,3.863899,Overall Inflation,National,Inflation Rate

In [11]:
def basic_checks(inflation_data):
    print('-' * 40, 'Shape', '-' * 40)
    print(inflation_data.shape)
    print('-' * 40, 'Columns', '-' * 40)
    print(inflation_data.columns)
    print('-' * 40, 'Info', '-' * 40)
    print(inflation_data.info())
    print('-' * 40, 'Summary statistics(categorical)', '-' * 40)
    print(display(inflation_data.describe(include=['str', 'object']).T))
    print('-' * 40, 'Summary statistics(numerical)', '-' * 40)
    print(display(inflation_data.describe(include=['int', 'float']).T))
    print('-' * 40, 'Duplicates', '-' * 40)
    print(inflation_data.duplicated().sum())
    print('-' * 40, 'Null Values', '-' * 40)
    print(inflation_data.isna().sum())
    print('-' * 40, 'Unique Values', '-' * 40)
    print(inflation_data.nunique())
    print('-' * 40, 'Data Types', '-' * 40)
    print(inflation_data.dtypes)

In [12]:
basic_checks(inflation_data)

---------------------------------------- Shape ----------------------------------------
(201, 8)
---------------------------------------- Columns ----------------------------------------
Index(['Period', 'Series', 'Value', 'Monthly Change (%)', 'Annual Change (%)',
       'Category', 'Region', 'Data Type'],
      dtype='str')
---------------------------------------- Info ----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Period              201 non-null    str
 1   Series              201 non-null    str
 2   Value               201 non-null    float64
 3   Monthly Change (%)  201 non-null    float64
 4   Annual Change (%)   201 non-null    float64
 5   Category            201 non-null    str
 6   Region              201 non-null    str
 7   Data Type           201 non-null    str
dtypes: float64(3), str(5)
memory usage: 12.7 KB
None
---------------------------------------- Summary statistics(categorical) ----------------------------------------

          count unique                           top freq
Period      201    201                    2010-01-01    1
Series      201      1  Overall Inflation (National)  201
Category    201      1             Overall Inflation  201
Region      201      1                      National  201
Data Type   201      1                Inflation Rate  201

None
---------------------------------------- Summary statistics(numerical) ----------------------------------------

,count,mean,std,min,25%,50%,75%,max
Value,201.0,6.621342,3.121779,2.728403,4.508043,6.086719,7.218132,19.709619
Monthly Change (%),201.0,0.537419,0.585660,-1.199917,0.221223,0.483158,0.893437,3.193851
Annual Change (%),201.0,6.621342,3.121779,2.728403,4.508043,6.086719,7.218132,19.709619

None
---------------------------------------- Duplicates ----------------------------------------
0
---------------------------------------- Null Values ----------------------------------------
Period                0
Series                0
Value                 0
Monthly Change (%)    0
Annual Change (%)     0
Category              0
Region                0
Data Type             0
dtype: int64
---------------------------------------- Unique Values ----------------------------------------
Period                201
Series                  1
Value                 201
Monthly Change (%)    201
Annual Change (%)     201
Category                1
Region                  1
Data Type               1
dtype: int64
---------------------------------------- Data Types ----------------------------------------
Period                    str
Series                    str
Value                 float64
Monthly Change (%)    float64
Annual Change (%)     float64
Category                  str
Region                    str
Data Type                 str
dtype: object

#### 4.) CPI values

In [13]:
cpi = pd.read_csv(r"C:\Users\Glemba\Desktop\Kenyan retail analysis\raw_data\kenya_cpi_values_2009-01-01_to_2026-09-01.csv")
cpi.head()

,Period,Series,Value,Monthly Change (%),Annual Change (%),Category,Region,Data Type
0,2009-01-01,Overall CPI (National),49.83,NaN,NaN,Overall CPI,National,Consumer Price Index
1,2009-02-01,Overall CPI (National),51.08,2.508529,NaN,Overall CPI,National,Consumer Price Index
2,2009-03-01,Overall CPI (National),51.57,0.959280,NaN,Overall CPI,National,Consumer Price Index
3,2009-04-01,Overall CPI (National),52.02,0.872600,NaN,Overall CPI,National,Consumer Price Index
4,2009-05-01,Overall CPI (National),52.02,0.000000,NaN,Overall CPI,National,Consumer Price Index

In [14]:
def basic_checks(cpi):
    print('-' * 40, 'Shape', '-' * 40)
    print(cpi.shape)
    print('-' * 40, 'Columns', '-' * 40)
    print(cpi.columns)
    print('-' * 40, 'Info', '-' * 40)
    print(cpi.info())
    print('-' * 40, 'Summary statistics(categorical)', '-' * 40)
    print(display(cpi.describe(include=['str', 'object']).T))
    print('-' * 40, 'Summary statistics(numerical)', '-' * 40)
    print(display(cpi.describe(include=['int', 'float']).T))
    print('-' * 40, 'Duplicates', '-' * 40)
    print(cpi.duplicated().sum())
    print('-' * 40, 'Null Values', '-' * 40)
    print(cpi.isna().sum())
    print('-' * 40, 'Unique Values', '-' * 40)
    print(cpi.nunique())
    print('-' * 40, 'Data Types', '-' * 40)
    print(cpi.dtypes)

In [15]:
basic_checks(cpi)

---------------------------------------- Shape ----------------------------------------
(213, 8)
---------------------------------------- Columns ----------------------------------------
Index(['Period', 'Series', 'Value', 'Monthly Change (%)', 'Annual Change (%)',
       'Category', 'Region', 'Data Type'],
      dtype='str')
---------------------------------------- Info ----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Period              213 non-null    str
 1   Series              213 non-null    str
 2   Value               213 non-null    float64
 3   Monthly Change (%)  212 non-null    float64
 4   Annual Change (%)   201 non-null    float64
 5   Category            213 non-null    str
 6   Region              213 non-null    str
 7   Data Type           213 non-null    str
dtypes: float64(3), str(5)
memory usage: 13.4 KB
None
---------------------------------------- Summary statistics(categorical) ----------------------------------------

          count unique                     top freq
Period      213    213              2009-01-01    1
Series      213      1  Overall CPI (National)  213
Category    213      1             Overall CPI  213
Region      213      1                National  213
Data Type   213      1    Consumer Price Index  213

None
---------------------------------------- Summary statistics(numerical) ----------------------------------------

,count,mean,std,min,25%,50%,75%,max
Value,213.0,97.388779,30.582359,49.830000,71.300000,94.740000,122.170000,156.470000
Monthly Change (%),212.0,0.542919,0.590189,-1.199917,0.220943,0.479312,0.892104,3.193851
Annual Change (%),201.0,6.621342,3.121779,2.728403,4.508043,6.086719,7.218132,19.709619

None
---------------------------------------- Duplicates ----------------------------------------
0
---------------------------------------- Null Values ----------------------------------------
Period                 0
Series                 0
Value                  0
Monthly Change (%)     1
Annual Change (%)     12
Category               0
Region                 0
Data Type              0
dtype: int64
---------------------------------------- Unique Values ----------------------------------------
Period                213
Series                  1
Value                 211
Monthly Change (%)    211
Annual Change (%)     201
Category                1
Region                  1
Data Type               1
dtype: int64
---------------------------------------- Data Types ----------------------------------------
Period                    str
Series                    str
Value                 float64
Monthly Change (%)    float64
Annual Change (%)     float64
Category                  str
Region                    str
Data Type                 str
dtype: object

#### 5.) Public holidays

In [19]:
holidays = pd.read_excel(r"C:\Users\Glemba\Desktop\Kenyan retail analysis\raw_data\kenya_public_holidays_2020_2026.xlsx")
holidays.head()

   Year    Holiday Name        Date Day of Week       Type
0  2020  New Year's Day  2020-01-01   Wednesday   National
1  2020     Good Friday  2020-04-10      Friday  Religious
2  2020   Easter Monday  2020-04-13      Monday  Religious
3  2020      Labour Day  2020-05-01      Friday   National
4  2020     Idd-ul-Fitr  2020-05-25      Monday  Religious

In [20]:
def basic_checks(holidays):
    print('-' * 40, 'Shape', '-' * 40)
    print(holidays.shape)
    print('-' * 40, 'Columns', '-' * 40)
    print(holidays.columns)
    print('-' * 40, 'Info', '-' * 40)
    print(holidays.info())
    print('-' * 40, 'Summary statistics(categorical)', '-' * 40)
    print(display(holidays.describe(include=['str', 'object']).T))
    print('-' * 40, 'Summary statistics(numerical)', '-' * 40)
    print(display(holidays.describe(include=['int', 'float']).T))
    print('-' * 40, 'Duplicates', '-' * 40)
    print(holidays.duplicated().sum())
    print('-' * 40, 'Null Values', '-' * 40)
    print(holidays.isna().sum())
    print('-' * 40, 'Unique Values', '-' * 40)
    print(holidays.nunique())
    print('-' * 40, 'Data Types', '-' * 40)
    print(holidays.dtypes)

In [21]:
basic_checks(holidays)

---------------------------------------- Shape ----------------------------------------
(84, 5)
---------------------------------------- Columns ----------------------------------------
Index(['Year', 'Holiday Name', 'Date', 'Day of Week', 'Type'], dtype='str')
---------------------------------------- Info ----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          84 non-null     int64
 1   Holiday Name  84 non-null     str
 2   Date          84 non-null     str
 3   Day of Week   84 non-null     str
 4   Type          84 non-null     str
dtypes: int64(1), str(4)
memory usage: 3.4 KB
None
---------------------------------------- Summary statistics(categorical) ----------------------------------------

             count unique             top freq
Holiday Name    84     14  New Year's Day    7
Date            84     84      2020-01-01    1
Day of Week     84      7          Friday   20
Type            84      2        National   56

None
---------------------------------------- Summary statistics(numerical) ----------------------------------------

      count    mean       std     min     25%     50%     75%     max
Year   84.0  2023.0  2.012012  2020.0  2021.0  2023.0  2025.0  2026.0

None
---------------------------------------- Duplicates ----------------------------------------
0
---------------------------------------- Null Values ----------------------------------------
Year            0
Holiday Name    0
Date            0
Day of Week     0
Type            0
dtype: int64
---------------------------------------- Unique Values ----------------------------------------
Year             7
Holiday Name    14
Date            84
Day of Week      7
Type             2
dtype: int64
---------------------------------------- Data Types ----------------------------------------
Year            int64
Holiday Name      str
Date              str
Day of Week       str
Type              str
dtype: object

### Export cleaned data

In [22]:
# define target folder and file path
output_folder = r"C:\Users\Glemba\Desktop\Kenyan retail analysis\cleaned_data"

files = {
    "shop_data.csv": shop_data,
    "population_data.csv": population_data,
    "inflation_data.csv": inflation_data,
    "cpi_data.csv": cpi,
    "holidays_data.csv": holidays
}

for file_name, df in files.items():
    file_path = os.path.join(output_folder, file_name)
    df.to_csv(file_path, index=False)
    print(f"Saved {file_name} to {file_path}")

Saved shop_data.csv to C:\Users\Glemba\Desktop\Kenyan retail analysis\cleaned_data\shop_data.csv
Saved population_data.csv to C:\Users\Glemba\Desktop\Kenyan retail analysis\cleaned_data\population_data.csv
Saved inflation_data.csv to C:\Users\Glemba\Desktop\Kenyan retail analysis\cleaned_data\inflation_data.csv
Saved cpi_data.csv to C:\Users\Glemba\Desktop\Kenyan retail analysis\cleaned_data\cpi_data.csv
Saved holidays_data.csv to C:\Users\Glemba\Desktop\Kenyan retail analysis\cleaned_data\holidays_data.csv